### PR TITLE
Moved Counter and tests to separate files, added tests for Counter, added byteorder option for Counter.

### PR DESCRIPTION
**Pull request by HolyGuacamole**

### CODE REVIEW

**Comment by Varbin** [comment]
Thank you! I've just looked over it and it looks good. I'll test this now out so I'll merge it probably in near future.

**Comment by HolyGuacamole** [comment]
I've moved the counter to a separate file, improved it with a byteorder option and added some test cases.
Can you accept merge this now?
I've made a class to compute CMAC's and I want to add that in another pull request.

**Comment by HolyGuacamole** [comment]
I've implemented your feedback.

Do you have more information about 64bits CMAC's being insecure?
It sounds interesting!

**Comment by Varbin** [comment]
CMACs are used to authenticate messages (MAC=message authentication code) to prwvent message forgery. Attackers can try to find a MAC for the new message. Usually 64-bit block size result in 64-bit tags. A so small tag size can easily forged.
While theoretically a block size can be increased (see Bruce Schneier's Applied Cryptography, Chapter Block ciphers) it makes it slower (additional encryption operations have to be done). When just two blocks are encrypted for creating the MAC tag
one block at a time must be "cracked" => 64-bit security.
Today 128-bit security is expected.
In all common security protocolls today MAC lengths of (at least) 80 to 128 (or more) are used.

**Comment by HolyGuacamole** [comment]
@Varbin Do you got a link to an example that shows that small tag sizes can easily be forged?
I'm not sure I understand how that would work.

**Pull request merged**
